apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: github-secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"ghcr.io":{"username":"firemanxbr","password":"ghp_example","auth":"ZmlyZW1hbnhicjpnaHBfZXhhbXBsZQ=="}}}
