apiVersion: sync.firemanxbr.dev/v1alpha1
kind: SecretClone
metadata:
  labels:
    app.kubernetes.io/name: go-operator-cloner
    app.kubernetes.io/managed-by: kustomize
  name: github-pull-secret
spec:
  sourceSecretRef:
    namespace: github-secrets
    name: github-pat
  targetSecretName: ghcr-pull-secret
  namespaceSelector:
    matchLabels:
      secret-sync.firemanxbr.dev/enabled: "true"
  excludedNamespaces:
    - kube-system
